services:
  backend:
    build: ./backend
    container_name: eulab-backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_migrations:/pb/pb_migrations
      - ./backend/pb_data:/pb/pb_data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eulab-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend
