services:
  backend:
    build: ./backend
    container_name: eulab-backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_migrations:/pb/pb_migrations
      - ./backend/pb_data:/pb/pb_data
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eulab-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
